language: bash

services:
  - docker

# pull existing releases, so docker build can leverage them via --cache-from
#
# (retrieval failure should be allowed in case this is the first time a variant
# is being built)
before_script:
  - docker pull openlaw/scala-builder:alpine && echo "OK" || echo "NOK"
  - docker pull openlaw/scala-builder:node   && echo "OK" || echo "NOK"

script:
  - make lint
  - make

after_success:
  - docker images
  - if [[ "$TRAVIS_TAG" =~ ^v[[:digit:]].* ]]; then
      echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin ;
      make publish ;
    fi

notifications:
  email: false
