language: bash

services:
  - docker

# pull existing releases, so docker build can leverage them via --cache-from
before_script:
  - docker pull openlaw/scala-builder:slim
  - docker pull openlaw/scala-builder:node

script:
  - make

after_success:
  - docker images
  - if [[ "$TRAVIS_TAG" =~ ^v[[:digit:]].* ]]; then
      echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin ;
      make publish ;
    fi

notifications:
  email: false
